### PR TITLE
Use bull v2

### PR DESCRIPTION
**Pull request by alanclarke**
- Affixes to next major version of bull
- Drops support for node <= 4.2
- Fixes tests & CI

### CODE REVIEW

**Comment by evanhuang8** [comment]
OK this is quite a big change so it might require some time to test & review, I will probably get to it the next few days

**Comment by alanclarke** [comment]
Well the intention was really to stabilise master, which is currently broken in CI and requires bull via git, which may include breaking changes, because it's not fixed to any major version

**Comment by alanclarke** [comment]
So fyi, master is already pulling in bull v2, because that is what is on the latest commit to the bull repo

**Comment by alanclarke** [comment]
@evanhuang8?

**Comment by woodardj** [comment]
Bump.

**Comment by jamesjjk** [comment]
+1

**Comment by alanclarke** [comment]
@evanhuang8?

**Comment by alanclarke** [comment]
So to summarise, currently this repo is not pointing to any specific version of bull right now. That means anyone trying to use it will pull in an unsupported version. if you merge this PR it will put this project into a usable state, and then you can relax and other people can use it 😄 

I'm cleaning up old PRs so I'm going to close this PR so if i don't hear back in a few days i'll close this

**Pull request closed without merging**
